import Head from "next/head";
import { useState, useEffect } from "react";
import { supabase } from "../api";
import Link from "next/link";
// import Image from 'next/image'

export function Header({title}){
  return(
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchPosts();
    const mySubscription = supabase
      .from('posts')
      .on('*', () => {
        console.log("something happened....");
        fetchPosts();
      })
      .subscribe();
    return () => supabase.removeSubscription(mySubscription);
  }, []);

  async function fetchPosts() {
    const { data, error } = await supabase.from('posts').select('*');
    console.log(data)
    setPosts(data);
    setLoading(false);
  }

  if (loading) return <p className="text-2xl">Loading ...</p>;
  if (!posts.length) return <p className="text-2xl">No posts.</p>;

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-0">
      <Header title="Create Next App"/>
      <h1 className="text-3xl font-semibold tracking-wide mt-6 mb-2">Posts</h1>
      
      <div className=" flex gap-3">
      {posts.map((post) => (
          <Link key={post.id} href={`/posts/${post.id}`}>
         <a className="border shadow rounded px-4 py-3 border-gray-300">
              <h2 className="text-xl font-semibold">{post.title}</h2>
              <p className="text-gray-500 mt-2">Author: {post.user_email}</p>
          </a>
        </Link>
      ))}
      </div>

    </div>
  );
}
